package seven.utils.dao;

import seven.utils.model.table.AuthProcessControl;
import seven.utils.model.table.AuthProcessControlKey;

import java.util.List;

public interface AuthProcessControlMapper {
    int deleteByPrimaryKey(AuthProcessControlKey key);

    int insert(AuthProcessControl record);

    int insertSelective(AuthProcessControl record);

    AuthProcessControl selectByPrimaryKey(AuthProcessControlKey key);

    int updateByPrimaryKeySelective(AuthProcessControl record);

    int updateByPrimaryKey(AuthProcessControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     * @return 交易执行组件列表
     */
    List<AuthProcessControl> selectControlListAsc(AuthProcessControlKey key);
}