package seven.utils.dao;

import org.apache.ibatis.annotations.Param;
import seven.utils.model.table.AuthProcessControl;
import seven.utils.model.table.AuthProcessControlExample;
import seven.utils.model.table.AuthProcessControlKey;

import java.util.List;

/**
 * 授权业务规则控制表
 * Created by moche_000 on 2019/8/23.
 */
public interface AuthProcessControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    long countByExample(AuthProcessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    int deleteByExample(AuthProcessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(AuthProcessControlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    int insert(AuthProcessControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    int insertSelective(AuthProcessControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    List<AuthProcessControl> selectByExample(AuthProcessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    AuthProcessControl selectByPrimaryKey(AuthProcessControlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthProcessControl record, @Param("example") AuthProcessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthProcessControl record, @Param("example") AuthProcessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthProcessControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthProcessControl record);
}