package seven.utils.model.table;

public class AuthProcessControlKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_process_control.pc_auth_trxn_code
     *
     * @mbg.generated
     */
    private String pcAuthTrxnCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_process_control.pc_step
     *
     * @mbg.generated
     */
    private Integer pcStep;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_process_control.pc_auth_trxn_code
     *
     * @return the value of auth_process_control.pc_auth_trxn_code
     *
     * @mbg.generated
     */
    public String getPcAuthTrxnCode() {
        return pcAuthTrxnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_process_control.pc_auth_trxn_code
     *
     * @param pcAuthTrxnCode the value for auth_process_control.pc_auth_trxn_code
     *
     * @mbg.generated
     */
    public void setPcAuthTrxnCode(String pcAuthTrxnCode) {
        this.pcAuthTrxnCode = pcAuthTrxnCode == null ? null : pcAuthTrxnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_process_control.pc_step
     *
     * @return the value of auth_process_control.pc_step
     *
     * @mbg.generated
     */
    public Integer getPcStep() {
        return pcStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_process_control.pc_step
     *
     * @param pcStep the value for auth_process_control.pc_step
     *
     * @mbg.generated
     */
    public void setPcStep(Integer pcStep) {
        this.pcStep = pcStep;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuthProcessControlKey other = (AuthProcessControlKey) that;
        return (this.getPcAuthTrxnCode() == null ? other.getPcAuthTrxnCode() == null : this.getPcAuthTrxnCode().equals(other.getPcAuthTrxnCode()))
            && (this.getPcStep() == null ? other.getPcStep() == null : this.getPcStep().equals(other.getPcStep()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPcAuthTrxnCode() == null) ? 0 : getPcAuthTrxnCode().hashCode());
        result = prime * result + ((getPcStep() == null) ? 0 : getPcStep().hashCode());
        return result;
    }
}