package seven.utils.model.table;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AuthProcessControlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    public AuthProcessControlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPcAuthTrxnCodeIsNull() {
            addCriterion("pc_auth_trxn_code is null");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeIsNotNull() {
            addCriterion("pc_auth_trxn_code is not null");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeEqualTo(String value) {
            addCriterion("pc_auth_trxn_code =", value, "pcAuthTrxnCode");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeNotEqualTo(String value) {
            addCriterion("pc_auth_trxn_code <>", value, "pcAuthTrxnCode");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeGreaterThan(String value) {
            addCriterion("pc_auth_trxn_code >", value, "pcAuthTrxnCode");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("pc_auth_trxn_code >=", value, "pcAuthTrxnCode");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeLessThan(String value) {
            addCriterion("pc_auth_trxn_code <", value, "pcAuthTrxnCode");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeLessThanOrEqualTo(String value) {
            addCriterion("pc_auth_trxn_code <=", value, "pcAuthTrxnCode");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeLike(String value) {
            addCriterion("pc_auth_trxn_code like", value, "pcAuthTrxnCode");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeNotLike(String value) {
            addCriterion("pc_auth_trxn_code not like", value, "pcAuthTrxnCode");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeIn(List<String> values) {
            addCriterion("pc_auth_trxn_code in", values, "pcAuthTrxnCode");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeNotIn(List<String> values) {
            addCriterion("pc_auth_trxn_code not in", values, "pcAuthTrxnCode");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeBetween(String value1, String value2) {
            addCriterion("pc_auth_trxn_code between", value1, value2, "pcAuthTrxnCode");
            return (Criteria) this;
        }

        public Criteria andPcAuthTrxnCodeNotBetween(String value1, String value2) {
            addCriterion("pc_auth_trxn_code not between", value1, value2, "pcAuthTrxnCode");
            return (Criteria) this;
        }

        public Criteria andPcStepIsNull() {
            addCriterion("pc_step is null");
            return (Criteria) this;
        }

        public Criteria andPcStepIsNotNull() {
            addCriterion("pc_step is not null");
            return (Criteria) this;
        }

        public Criteria andPcStepEqualTo(Integer value) {
            addCriterion("pc_step =", value, "pcStep");
            return (Criteria) this;
        }

        public Criteria andPcStepNotEqualTo(Integer value) {
            addCriterion("pc_step <>", value, "pcStep");
            return (Criteria) this;
        }

        public Criteria andPcStepGreaterThan(Integer value) {
            addCriterion("pc_step >", value, "pcStep");
            return (Criteria) this;
        }

        public Criteria andPcStepGreaterThanOrEqualTo(Integer value) {
            addCriterion("pc_step >=", value, "pcStep");
            return (Criteria) this;
        }

        public Criteria andPcStepLessThan(Integer value) {
            addCriterion("pc_step <", value, "pcStep");
            return (Criteria) this;
        }

        public Criteria andPcStepLessThanOrEqualTo(Integer value) {
            addCriterion("pc_step <=", value, "pcStep");
            return (Criteria) this;
        }

        public Criteria andPcStepIn(List<Integer> values) {
            addCriterion("pc_step in", values, "pcStep");
            return (Criteria) this;
        }

        public Criteria andPcStepNotIn(List<Integer> values) {
            addCriterion("pc_step not in", values, "pcStep");
            return (Criteria) this;
        }

        public Criteria andPcStepBetween(Integer value1, Integer value2) {
            addCriterion("pc_step between", value1, value2, "pcStep");
            return (Criteria) this;
        }

        public Criteria andPcStepNotBetween(Integer value1, Integer value2) {
            addCriterion("pc_step not between", value1, value2, "pcStep");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanIsNull() {
            addCriterion("pc_component_bean is null");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanIsNotNull() {
            addCriterion("pc_component_bean is not null");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanEqualTo(String value) {
            addCriterion("pc_component_bean =", value, "pcComponentBean");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanNotEqualTo(String value) {
            addCriterion("pc_component_bean <>", value, "pcComponentBean");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanGreaterThan(String value) {
            addCriterion("pc_component_bean >", value, "pcComponentBean");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanGreaterThanOrEqualTo(String value) {
            addCriterion("pc_component_bean >=", value, "pcComponentBean");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanLessThan(String value) {
            addCriterion("pc_component_bean <", value, "pcComponentBean");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanLessThanOrEqualTo(String value) {
            addCriterion("pc_component_bean <=", value, "pcComponentBean");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanLike(String value) {
            addCriterion("pc_component_bean like", value, "pcComponentBean");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanNotLike(String value) {
            addCriterion("pc_component_bean not like", value, "pcComponentBean");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanIn(List<String> values) {
            addCriterion("pc_component_bean in", values, "pcComponentBean");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanNotIn(List<String> values) {
            addCriterion("pc_component_bean not in", values, "pcComponentBean");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanBetween(String value1, String value2) {
            addCriterion("pc_component_bean between", value1, value2, "pcComponentBean");
            return (Criteria) this;
        }

        public Criteria andPcComponentBeanNotBetween(String value1, String value2) {
            addCriterion("pc_component_bean not between", value1, value2, "pcComponentBean");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeIsNull() {
            addCriterion("pc_error_process_type is null");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeIsNotNull() {
            addCriterion("pc_error_process_type is not null");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeEqualTo(String value) {
            addCriterion("pc_error_process_type =", value, "pcErrorProcessType");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeNotEqualTo(String value) {
            addCriterion("pc_error_process_type <>", value, "pcErrorProcessType");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeGreaterThan(String value) {
            addCriterion("pc_error_process_type >", value, "pcErrorProcessType");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeGreaterThanOrEqualTo(String value) {
            addCriterion("pc_error_process_type >=", value, "pcErrorProcessType");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeLessThan(String value) {
            addCriterion("pc_error_process_type <", value, "pcErrorProcessType");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeLessThanOrEqualTo(String value) {
            addCriterion("pc_error_process_type <=", value, "pcErrorProcessType");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeLike(String value) {
            addCriterion("pc_error_process_type like", value, "pcErrorProcessType");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeNotLike(String value) {
            addCriterion("pc_error_process_type not like", value, "pcErrorProcessType");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeIn(List<String> values) {
            addCriterion("pc_error_process_type in", values, "pcErrorProcessType");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeNotIn(List<String> values) {
            addCriterion("pc_error_process_type not in", values, "pcErrorProcessType");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeBetween(String value1, String value2) {
            addCriterion("pc_error_process_type between", value1, value2, "pcErrorProcessType");
            return (Criteria) this;
        }

        public Criteria andPcErrorProcessTypeNotBetween(String value1, String value2) {
            addCriterion("pc_error_process_type not between", value1, value2, "pcErrorProcessType");
            return (Criteria) this;
        }

        public Criteria andPcGotoStepIsNull() {
            addCriterion("pc_goto_step is null");
            return (Criteria) this;
        }

        public Criteria andPcGotoStepIsNotNull() {
            addCriterion("pc_goto_step is not null");
            return (Criteria) this;
        }

        public Criteria andPcGotoStepEqualTo(Integer value) {
            addCriterion("pc_goto_step =", value, "pcGotoStep");
            return (Criteria) this;
        }

        public Criteria andPcGotoStepNotEqualTo(Integer value) {
            addCriterion("pc_goto_step <>", value, "pcGotoStep");
            return (Criteria) this;
        }

        public Criteria andPcGotoStepGreaterThan(Integer value) {
            addCriterion("pc_goto_step >", value, "pcGotoStep");
            return (Criteria) this;
        }

        public Criteria andPcGotoStepGreaterThanOrEqualTo(Integer value) {
            addCriterion("pc_goto_step >=", value, "pcGotoStep");
            return (Criteria) this;
        }

        public Criteria andPcGotoStepLessThan(Integer value) {
            addCriterion("pc_goto_step <", value, "pcGotoStep");
            return (Criteria) this;
        }

        public Criteria andPcGotoStepLessThanOrEqualTo(Integer value) {
            addCriterion("pc_goto_step <=", value, "pcGotoStep");
            return (Criteria) this;
        }

        public Criteria andPcGotoStepIn(List<Integer> values) {
            addCriterion("pc_goto_step in", values, "pcGotoStep");
            return (Criteria) this;
        }

        public Criteria andPcGotoStepNotIn(List<Integer> values) {
            addCriterion("pc_goto_step not in", values, "pcGotoStep");
            return (Criteria) this;
        }

        public Criteria andPcGotoStepBetween(Integer value1, Integer value2) {
            addCriterion("pc_goto_step between", value1, value2, "pcGotoStep");
            return (Criteria) this;
        }

        public Criteria andPcGotoStepNotBetween(Integer value1, Integer value2) {
            addCriterion("pc_goto_step not between", value1, value2, "pcGotoStep");
            return (Criteria) this;
        }

        public Criteria andPcCreateTimeIsNull() {
            addCriterion("pc_create_time is null");
            return (Criteria) this;
        }

        public Criteria andPcCreateTimeIsNotNull() {
            addCriterion("pc_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andPcCreateTimeEqualTo(Date value) {
            addCriterion("pc_create_time =", value, "pcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPcCreateTimeNotEqualTo(Date value) {
            addCriterion("pc_create_time <>", value, "pcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPcCreateTimeGreaterThan(Date value) {
            addCriterion("pc_create_time >", value, "pcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPcCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("pc_create_time >=", value, "pcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPcCreateTimeLessThan(Date value) {
            addCriterion("pc_create_time <", value, "pcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPcCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("pc_create_time <=", value, "pcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPcCreateTimeIn(List<Date> values) {
            addCriterion("pc_create_time in", values, "pcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPcCreateTimeNotIn(List<Date> values) {
            addCriterion("pc_create_time not in", values, "pcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPcCreateTimeBetween(Date value1, Date value2) {
            addCriterion("pc_create_time between", value1, value2, "pcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPcCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("pc_create_time not between", value1, value2, "pcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserIsNull() {
            addCriterion("pc_create_user is null");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserIsNotNull() {
            addCriterion("pc_create_user is not null");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserEqualTo(String value) {
            addCriterion("pc_create_user =", value, "pcCreateUser");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserNotEqualTo(String value) {
            addCriterion("pc_create_user <>", value, "pcCreateUser");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserGreaterThan(String value) {
            addCriterion("pc_create_user >", value, "pcCreateUser");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("pc_create_user >=", value, "pcCreateUser");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserLessThan(String value) {
            addCriterion("pc_create_user <", value, "pcCreateUser");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserLessThanOrEqualTo(String value) {
            addCriterion("pc_create_user <=", value, "pcCreateUser");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserLike(String value) {
            addCriterion("pc_create_user like", value, "pcCreateUser");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserNotLike(String value) {
            addCriterion("pc_create_user not like", value, "pcCreateUser");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserIn(List<String> values) {
            addCriterion("pc_create_user in", values, "pcCreateUser");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserNotIn(List<String> values) {
            addCriterion("pc_create_user not in", values, "pcCreateUser");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserBetween(String value1, String value2) {
            addCriterion("pc_create_user between", value1, value2, "pcCreateUser");
            return (Criteria) this;
        }

        public Criteria andPcCreateUserNotBetween(String value1, String value2) {
            addCriterion("pc_create_user not between", value1, value2, "pcCreateUser");
            return (Criteria) this;
        }

        public Criteria andPcUpdateTimeIsNull() {
            addCriterion("pc_update_time is null");
            return (Criteria) this;
        }

        public Criteria andPcUpdateTimeIsNotNull() {
            addCriterion("pc_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andPcUpdateTimeEqualTo(Date value) {
            addCriterion("pc_update_time =", value, "pcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPcUpdateTimeNotEqualTo(Date value) {
            addCriterion("pc_update_time <>", value, "pcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPcUpdateTimeGreaterThan(Date value) {
            addCriterion("pc_update_time >", value, "pcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPcUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("pc_update_time >=", value, "pcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPcUpdateTimeLessThan(Date value) {
            addCriterion("pc_update_time <", value, "pcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPcUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("pc_update_time <=", value, "pcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPcUpdateTimeIn(List<Date> values) {
            addCriterion("pc_update_time in", values, "pcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPcUpdateTimeNotIn(List<Date> values) {
            addCriterion("pc_update_time not in", values, "pcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPcUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("pc_update_time between", value1, value2, "pcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPcUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("pc_update_time not between", value1, value2, "pcUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserIsNull() {
            addCriterion("pc_update_user is null");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserIsNotNull() {
            addCriterion("pc_update_user is not null");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserEqualTo(String value) {
            addCriterion("pc_update_user =", value, "pcUpdateUser");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserNotEqualTo(String value) {
            addCriterion("pc_update_user <>", value, "pcUpdateUser");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserGreaterThan(String value) {
            addCriterion("pc_update_user >", value, "pcUpdateUser");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("pc_update_user >=", value, "pcUpdateUser");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserLessThan(String value) {
            addCriterion("pc_update_user <", value, "pcUpdateUser");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("pc_update_user <=", value, "pcUpdateUser");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserLike(String value) {
            addCriterion("pc_update_user like", value, "pcUpdateUser");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserNotLike(String value) {
            addCriterion("pc_update_user not like", value, "pcUpdateUser");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserIn(List<String> values) {
            addCriterion("pc_update_user in", values, "pcUpdateUser");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserNotIn(List<String> values) {
            addCriterion("pc_update_user not in", values, "pcUpdateUser");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserBetween(String value1, String value2) {
            addCriterion("pc_update_user between", value1, value2, "pcUpdateUser");
            return (Criteria) this;
        }

        public Criteria andPcUpdateUserNotBetween(String value1, String value2) {
            addCriterion("pc_update_user not between", value1, value2, "pcUpdateUser");
            return (Criteria) this;
        }

        public Criteria andPcVersionIsNull() {
            addCriterion("pc_version is null");
            return (Criteria) this;
        }

        public Criteria andPcVersionIsNotNull() {
            addCriterion("pc_version is not null");
            return (Criteria) this;
        }

        public Criteria andPcVersionEqualTo(Integer value) {
            addCriterion("pc_version =", value, "pcVersion");
            return (Criteria) this;
        }

        public Criteria andPcVersionNotEqualTo(Integer value) {
            addCriterion("pc_version <>", value, "pcVersion");
            return (Criteria) this;
        }

        public Criteria andPcVersionGreaterThan(Integer value) {
            addCriterion("pc_version >", value, "pcVersion");
            return (Criteria) this;
        }

        public Criteria andPcVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("pc_version >=", value, "pcVersion");
            return (Criteria) this;
        }

        public Criteria andPcVersionLessThan(Integer value) {
            addCriterion("pc_version <", value, "pcVersion");
            return (Criteria) this;
        }

        public Criteria andPcVersionLessThanOrEqualTo(Integer value) {
            addCriterion("pc_version <=", value, "pcVersion");
            return (Criteria) this;
        }

        public Criteria andPcVersionIn(List<Integer> values) {
            addCriterion("pc_version in", values, "pcVersion");
            return (Criteria) this;
        }

        public Criteria andPcVersionNotIn(List<Integer> values) {
            addCriterion("pc_version not in", values, "pcVersion");
            return (Criteria) this;
        }

        public Criteria andPcVersionBetween(Integer value1, Integer value2) {
            addCriterion("pc_version between", value1, value2, "pcVersion");
            return (Criteria) this;
        }

        public Criteria andPcVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("pc_version not between", value1, value2, "pcVersion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auth_process_control
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}