package seven.utils.model.table;

import java.util.Date;

public class AuthProcessControl extends AuthProcessControlKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_process_control.pc_component_bean
     *
     * @mbg.generated
     */
    private String pcComponentBean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_process_control.pc_error_process_type
     *
     * @mbg.generated
     */
    private String pcErrorProcessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_process_control.pc_goto_step
     *
     * @mbg.generated
     */
    private Integer pcGotoStep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_process_control.pc_create_time
     *
     * @mbg.generated
     */
    private Date pcCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_process_control.pc_create_user
     *
     * @mbg.generated
     */
    private String pcCreateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_process_control.pc_update_time
     *
     * @mbg.generated
     */
    private Date pcUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_process_control.pc_update_user
     *
     * @mbg.generated
     */
    private String pcUpdateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_process_control.pc_version
     *
     * @mbg.generated
     */
    private Integer pcVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_process_control.pc_component_bean
     *
     * @return the value of auth_process_control.pc_component_bean
     *
     * @mbg.generated
     */
    public String getPcComponentBean() {
        return pcComponentBean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_process_control.pc_component_bean
     *
     * @param pcComponentBean the value for auth_process_control.pc_component_bean
     *
     * @mbg.generated
     */
    public void setPcComponentBean(String pcComponentBean) {
        this.pcComponentBean = pcComponentBean == null ? null : pcComponentBean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_process_control.pc_error_process_type
     *
     * @return the value of auth_process_control.pc_error_process_type
     *
     * @mbg.generated
     */
    public String getPcErrorProcessType() {
        return pcErrorProcessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_process_control.pc_error_process_type
     *
     * @param pcErrorProcessType the value for auth_process_control.pc_error_process_type
     *
     * @mbg.generated
     */
    public void setPcErrorProcessType(String pcErrorProcessType) {
        this.pcErrorProcessType = pcErrorProcessType == null ? null : pcErrorProcessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_process_control.pc_goto_step
     *
     * @return the value of auth_process_control.pc_goto_step
     *
     * @mbg.generated
     */
    public Integer getPcGotoStep() {
        return pcGotoStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_process_control.pc_goto_step
     *
     * @param pcGotoStep the value for auth_process_control.pc_goto_step
     *
     * @mbg.generated
     */
    public void setPcGotoStep(Integer pcGotoStep) {
        this.pcGotoStep = pcGotoStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_process_control.pc_create_time
     *
     * @return the value of auth_process_control.pc_create_time
     *
     * @mbg.generated
     */
    public Date getPcCreateTime() {
        return pcCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_process_control.pc_create_time
     *
     * @param pcCreateTime the value for auth_process_control.pc_create_time
     *
     * @mbg.generated
     */
    public void setPcCreateTime(Date pcCreateTime) {
        this.pcCreateTime = pcCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_process_control.pc_create_user
     *
     * @return the value of auth_process_control.pc_create_user
     *
     * @mbg.generated
     */
    public String getPcCreateUser() {
        return pcCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_process_control.pc_create_user
     *
     * @param pcCreateUser the value for auth_process_control.pc_create_user
     *
     * @mbg.generated
     */
    public void setPcCreateUser(String pcCreateUser) {
        this.pcCreateUser = pcCreateUser == null ? null : pcCreateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_process_control.pc_update_time
     *
     * @return the value of auth_process_control.pc_update_time
     *
     * @mbg.generated
     */
    public Date getPcUpdateTime() {
        return pcUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_process_control.pc_update_time
     *
     * @param pcUpdateTime the value for auth_process_control.pc_update_time
     *
     * @mbg.generated
     */
    public void setPcUpdateTime(Date pcUpdateTime) {
        this.pcUpdateTime = pcUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_process_control.pc_update_user
     *
     * @return the value of auth_process_control.pc_update_user
     *
     * @mbg.generated
     */
    public String getPcUpdateUser() {
        return pcUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_process_control.pc_update_user
     *
     * @param pcUpdateUser the value for auth_process_control.pc_update_user
     *
     * @mbg.generated
     */
    public void setPcUpdateUser(String pcUpdateUser) {
        this.pcUpdateUser = pcUpdateUser == null ? null : pcUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_process_control.pc_version
     *
     * @return the value of auth_process_control.pc_version
     *
     * @mbg.generated
     */
    public Integer getPcVersion() {
        return pcVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_process_control.pc_version
     *
     * @param pcVersion the value for auth_process_control.pc_version
     *
     * @mbg.generated
     */
    public void setPcVersion(Integer pcVersion) {
        this.pcVersion = pcVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPcAuthTrxnCode() == null) ? 0 : getPcAuthTrxnCode().hashCode());
        result = prime * result + ((getPcStep() == null) ? 0 : getPcStep().hashCode());
        result = prime * result + ((getPcComponentBean() == null) ? 0 : getPcComponentBean().hashCode());
        result = prime * result + ((getPcErrorProcessType() == null) ? 0 : getPcErrorProcessType().hashCode());
        result = prime * result + ((getPcGotoStep() == null) ? 0 : getPcGotoStep().hashCode());
        result = prime * result + ((getPcCreateTime() == null) ? 0 : getPcCreateTime().hashCode());
        result = prime * result + ((getPcCreateUser() == null) ? 0 : getPcCreateUser().hashCode());
        result = prime * result + ((getPcUpdateTime() == null) ? 0 : getPcUpdateTime().hashCode());
        result = prime * result + ((getPcUpdateUser() == null) ? 0 : getPcUpdateUser().hashCode());
        result = prime * result + ((getPcVersion() == null) ? 0 : getPcVersion().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_process_control
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuthProcessControl other = (AuthProcessControl) that;
        return (this.getPcAuthTrxnCode() == null ? other.getPcAuthTrxnCode() == null : this.getPcAuthTrxnCode().equals(other.getPcAuthTrxnCode()))
            && (this.getPcStep() == null ? other.getPcStep() == null : this.getPcStep().equals(other.getPcStep()))
            && (this.getPcComponentBean() == null ? other.getPcComponentBean() == null : this.getPcComponentBean().equals(other.getPcComponentBean()))
            && (this.getPcErrorProcessType() == null ? other.getPcErrorProcessType() == null : this.getPcErrorProcessType().equals(other.getPcErrorProcessType()))
            && (this.getPcGotoStep() == null ? other.getPcGotoStep() == null : this.getPcGotoStep().equals(other.getPcGotoStep()))
            && (this.getPcCreateTime() == null ? other.getPcCreateTime() == null : this.getPcCreateTime().equals(other.getPcCreateTime()))
            && (this.getPcCreateUser() == null ? other.getPcCreateUser() == null : this.getPcCreateUser().equals(other.getPcCreateUser()))
            && (this.getPcUpdateTime() == null ? other.getPcUpdateTime() == null : this.getPcUpdateTime().equals(other.getPcUpdateTime()))
            && (this.getPcUpdateUser() == null ? other.getPcUpdateUser() == null : this.getPcUpdateUser().equals(other.getPcUpdateUser()))
            && (this.getPcVersion() == null ? other.getPcVersion() == null : this.getPcVersion().equals(other.getPcVersion()));
    }


}